'use strict';
const test=require('node:test'), assert=require('node:assert/strict');
const fs=require('node:fs'), path=require('node:path'), os=require('node:os'), vm=require('node:vm');
const {createServer}=require('node:http'), {execFileSync}=require('node:child_process');
const {readInputs,assemble,rollbackRelease,sha256}=require('./build.cjs');
const ROOT=path.resolve(__dirname,'..'), EVID=path.resolve(process.env.PHEISIRAETHA_2B4_EVIDENCE);
const MAIN='255a5d9d27461dcacaebc1bc80ab322dd54b4de8';
const ART='browser-packaging/artifacts/analytics-v1.f1f975900faaa64649bcef42412c1856543c8716711d4119df9b964f4bf8c824.js';
const IDS=['OFF-01','INSTALL-01','FETCH-01','HASH-01','QUOTA-01','COLD-00','COLD-01','WARM-01','CACHE-01','MIX-01','MIX-02','UPGRADE-01','DIGEST-01','ON-01','STORE-01','ROLLBACK-01'];
const KEY='pheisiraetha_v01', LANG='pheisiraetha_language_v01', ONBOARD='pheisiraetha_onboarding_v01';
const HOST='#app > .shell > main > #analyticsHost', rows=new Map(), extras=[], failures=[];
const git=(...a)=>execFileSync('git',['--no-optional-locks','-C',ROOT,...a],{encoding:'utf8',env:{...process.env,GIT_OPTIONAL_LOCKS:'0',GIT_NO_REPLACE_OBJECTS:'1'}}).trim();
assert.equal(process.platform,'linux'); assert.equal(process.version,'v24.19.0');
assert.equal(require('playwright/package.json').version,'1.62.1');
const external=fs.realpathSync(require.resolve('playwright/package.json'));
assert.ok(!external.startsWith(ROOT+path.sep),'External Playwright required');
const chromium=require('playwright').chromium, browserPath=fs.realpathSync(process.env.LEGACY_DOM_CHROMIUM_EXECUTABLE_PATH);
const browserBefore=sha256(fs.readFileSync(browserPath)), initialGit=git('status','--porcelain');
assert.equal(initialGit,''); const evidenceRelative=path.relative(ROOT,EVID); assert.ok(evidenceRelative==='..'||evidenceRelative.startsWith('..'+path.sep)||path.isAbsolute(evidenceRelative),'Evidence must remain outside checkout'); fs.mkdirSync(EVID,{recursive:true});
const inputs=readInputs(ROOT), primary=assemble({...inputs,generation:'offline-candidate-01'});
const fixtures=require(path.join(ROOT,'browser-packaging/runtime-core/fixtures.cjs'));
const labels=Array(10).fill('Calm / contentment'), mf3=fixtures.reflection(labels,'B4',true), mf4=fixtures.fixture(1,labels), empty=fixtures.fixture(0,labels);
const artifact=inputs.candidate.get(ART), legacyWorker=Buffer.from(execFileSync('git',['-C',ROOT,'show',MAIN+':sw.js']));
assert.equal(sha256(legacyWorker),inputs.legacyWorkerSha256);
function oracle(source){const r=vm.createContext({input:JSON.stringify(source)});vm.runInContext(artifact.toString(),r,{timeout:10000});return JSON.parse(vm.runInContext('JSON.stringify(PHEISIRAETHA_ANALYTICS_V1.evaluate(JSON.parse(input)))',r,{timeout:10000}));}
assert.equal(oracle(mf3).components.length,5); assert.equal(oracle(mf4).components.length,9); assert.equal(oracle(empty).mode,'FALLBACK_ONLY');
let generation=1, cases=0, browserVersion, installWitness;
async function bounded(p,ms=30000){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Browser lifecycle timeout')),ms);})]);}finally{clearTimeout(timer);}}
function release(enabled=false){const candidate=new Map(inputs.candidate);if(enabled){const s=candidate.get('app.js').toString(),old='const ANALYTICS_ENABLED = false;';assert.equal(s.split(old).length,2);candidate.set('app.js',Buffer.from(s.replace(old,'const ANALYTICS_ENABLED = true;')));}return assemble({...inputs,candidate,generation:'offline-candidate-'+String(++generation).padStart(2,'0'),privateFixture:enabled});}
function row(id,witnesses){assert.ok(IDS.includes(id));assert.ok(!rows.has(id),'Duplicate row '+id);rows.set(id,{id,status:'PASS',witnesses});}
function type(url){return url==='__seed'?'text/html':/\.html$/.test(url)?'text/html':/\.js$/.test(url)?'text/javascript':/\.css$/.test(url)?'text/css':/\.webmanifest$/.test(url)?'application/manifest+json':/\.png$/.test(url)?'image/png':/\.jpg$/.test(url)?'image/jpeg':'application/octet-stream';}
async function environment(source=mf4){
 const s={current:legacyWorker,aliases:new Map(),fault:null,offline:false,requests:[],profile:fs.mkdtempSync(path.join(os.tmpdir(),'pheisiraetha-2b4-')),context:null};
 s.server=createServer((req,res)=>{const u=new URL(req.url,'http://localhost'), key=u.pathname.slice(1)+(u.search||''), physical=u.pathname.slice(1)||'index.html';let bytes;
  if(physical==='sw.js')bytes=s.current;else if(physical==='__seed')bytes=Buffer.from('<!doctype html><title>seed</title>');else if(physical==='index.html'&&s.bootstrap)bytes=s.bootstrap;else if(inputs.legacy.has(physical))bytes=inputs.legacy.get(physical);else bytes=s.aliases.get(key)||s.aliases.get(physical);
  const mode=s.fault&&s.fault.url===key?s.fault.kind:null;
  s.requests.push({url:key,method:req.method,mode,offline:s.offline,sha256:bytes&&sha256(bytes)});
  if(s.offline||mode==='interrupt'){res.destroy();return;} if(mode==='redirect'){res.writeHead(302,{Location:'/__seed'});res.end();return;}
  if(!bytes||mode==='404'||mode==='500'){res.writeHead(mode==='500'?500:404);res.end('missing');return;}
  if(mode==='hash')bytes=Buffer.concat([Buffer.from('!'),bytes.subarray(1)]); if(mode==='size')bytes=Buffer.concat([bytes,Buffer.from('!')]);
  if(mode==='bootstrap')bytes=Buffer.concat([bytes,Buffer.from('\n;globalThis.__privateBootstrapCorruptionExecuted=true;\n')]);
  res.writeHead(200,{'Content-Type':type(physical),'Cache-Control':'no-store','Service-Worker-Allowed':'/'});res.end(bytes);
 });
 await new Promise(r=>s.server.listen(0,'127.0.0.1',r));s.origin='http://127.0.0.1:'+s.server.address().port;
 s.start=async()=>{s.context=await chromium.launchPersistentContext(s.profile,{headless:true,executablePath:browserPath,serviceWorkers:'allow'});browserVersion=s.context.browser().version();s.context.on('page',p=>p.on('dialog',d=>d.accept()));for(const p of s.context.pages())p.on('dialog',d=>d.accept());return s.context.pages()[0]||s.context.newPage();};
 try{const p=await s.start();await p.goto(s.origin+'/__seed');await p.evaluate(({source,KEY,LANG,ONBOARD})=>{localStorage.setItem(KEY,JSON.stringify(source));localStorage.setItem(LANG,'en');localStorage.setItem(ONBOARD,'1');},{source,KEY,LANG,ONBOARD});s.page=p;return s;}catch(error){await dispose(s);throw error;}
}
async function closeServer(server){server.closeAllConnections();await bounded(new Promise(resolve=>server.close(resolve)),5000);}
async function dispose(s){try{if(s.context)await bounded(s.context.close(),10000);}finally{await closeServer(s.server);}}
async function normal(p,s){await p.goto(s.origin+'/');await p.waitForFunction(()=>!document.body.classList.contains('is-launching'));assert.equal(await p.locator('#startCheckin').isVisible(),true);}
async function legacy(s){
 await normal(s.page,s);
 await s.page.waitForFunction(async()=>{const r=await navigator.serviceWorker.getRegistration();return Boolean(navigator.serviceWorker.controller&&r?.active?.state==='activated');});
 const assets=primary.inventory.assets.filter(a=>inputs.legacy.has(a.url.split('?')[0])).map(a=>{const bytes=inputs.legacy.get(a.url.split('?')[0]);return {url:a.url,sha256:sha256(bytes),sizeBytes:bytes.length};});
 s.legacyWitness=await s.page.evaluate(async assets=>{const names=await caches.keys();if(!names.includes('pheisiraetha-v16'))throw Error('Established v16 cache missing');const c=await caches.open('pheisiraetha-v16');for(const a of assets){const response=await c.match(new URL(a.url,location.origin+'/'));if(!response)throw Error('Established v16 asset missing: '+a.url);const bytes=await response.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(bytes.byteLength!==a.sizeBytes||hash!==a.sha256)throw Error('Established v16 asset identity: '+a.url);}const r=await navigator.serviceWorker.getRegistration();return {cacheName:'pheisiraetha-v16',verifiedAssetCount:assets.length,activeState:r.active.state,controllerURL:navigator.serviceWorker.controller.scriptURL,cacheNamesBeforeCandidate:names};},assets);
 assert.equal(s.legacyWitness.activeState,'activated');
}
function publish(s,r){const bootstrap=r.files.get('index.html');assert.equal(bootstrap.toString().replace(/ integrity="sha256-[^"]+" crossorigin="anonymous"/g,''),inputs.legacy.get('index.html').toString());assert.equal((bootstrap.toString().match(/integrity="sha256-/g)||[]).length,4);s.bootstrap=bootstrap;for(const[url,bytes]of r.assets){const physical=url.split('?')[0];if(inputs.legacy.has(physical)&&physical!=='index.html')assert.deepEqual(bytes,inputs.legacy.get(physical));s.aliases.set(url,bytes);}s.current=r.worker;}
async function waiting(s,r){
 publish(s,r);const event=s.context.waitForEvent('serviceworker',{timeout:30000});await s.page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();await registration.update();});const w=await event;
 await s.page.waitForFunction(()=>navigator.serviceWorker.getRegistration().then(registration=>registration.waiting?.state==='installed'));
 const identity=await w.evaluate(()=>({releaseDigest:CONFIG.releaseDigest,cacheName:CONFIG.cacheName,entryURL:CONFIG.inventory.entryURL,scope:self.registration.scope}));
 assert.equal(identity.releaseDigest,r.releaseDigest,'Observed waiting worker digest');assert.equal(identity.cacheName,r.cacheName,'Observed waiting worker cache');assert.equal(identity.entryURL,r.entryURL,'Observed waiting worker entry');assert.equal(identity.scope,s.origin+'/');s.waitingWitness=identity;return w;
}
async function activate(s,w){const ready=w.evaluate(()=>new Promise(resolve=>self.addEventListener('activate',()=>resolve(true),{once:true})));for(const p of s.context.pages())await bounded(p.close());await bounded(ready);await bounded(w.evaluate(()=>new Promise(resolve=>{const check=()=>self.registration.active?.state==='activated'?resolve(true):setTimeout(check,30);check();})));s.page=await s.context.newPage();await normal(s.page,s);}
async function complete(s,r){return s.page.evaluate(async({cacheName,sealURL,prefix,assets,releaseDigest})=>{
 const names=await caches.keys(),registration=await navigator.serviceWorker.getRegistration(),base=location.origin+'/',url=new URL(sealURL,base).href;
 const state={requestedCache:cacheName,cacheNames:names,sealURL:url,activeState:registration?.active?.state,waitingState:registration?.waiting?.state,controllerURL:navigator.serviceWorker.controller?.scriptURL};
 if(!names.includes(cacheName))throw Error('Complete release cache absent: '+JSON.stringify(state));
 const cache=await caches.open(cacheName),marker=await cache.match(url),markerText=marker?await marker.text():null,keys=await cache.keys();
 if(!marker||marker.status!==200||markerText!==JSON.stringify({releaseDigest,assetCount:assets.length,complete:true}))throw Error('Invalid completion marker: '+JSON.stringify({...state,markerStatus:marker?.status,markerText,keys:keys.map(k=>k.url)}));
 if(keys.length!==assets.length+1)throw Error('Unexpected cache entry count');
 for(const a of assets){const k=new URL(prefix+encodeURIComponent(a.url),base),res=await cache.match(k);if(!res)throw Error('Missing '+a.url);const b=await res.arrayBuffer(),digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');if(b.byteLength!==a.sizeBytes||digest!==a.sha256)throw Error('Wrong cached '+a.url);}
 return {cacheName,entryCount:keys.length,sealURL,sealVerified:true};
 },{cacheName:r.cacheName,sealURL:r.sealURL,prefix:r.cacheKeyPrefix,assets:r.inventory.assets,releaseDigest:r.releaseDigest});
}
async function storage(s){const value=await s.page.evaluate(async({KEY,LANG,ONBOARD})=>({keys:Object.keys(localStorage).sort(),state:JSON.parse(localStorage.getItem(KEY)),databases:(await indexedDB.databases()).map(x=>x.name),caches:await caches.keys()}),{KEY,LANG,ONBOARD});assert.deepEqual(value.keys,[KEY,LANG,ONBOARD].sort());assert.deepEqual(value.databases,[]);assert.equal(value.state.version,'0.1.0');assert.deepEqual(Object.keys(value.state).sort(),['intent','lang','version']);assert.ok(s.requests.every(x=>x.method==='GET'));assert.ok(s.requests.every(x=>!/(synthetic-core|Synthetic%20)/.test(x.url)));return value;}
async function analytics(p,source){const expected=oracle(source),texts=await p.locator(HOST+' section.card > p').allTextContents();assert.deepEqual(texts,expected.components.map(c=>c.text));assert.equal(await p.locator(HOST+' section.card').getAttribute('lang'),'en');assert.equal(await p.locator(HOST+' section.card').getAttribute('dir'),'ltr');const all=await p.locator(HOST).evaluate(h=>({ids:[...h.querySelectorAll('[id]')].map(x=>x.id),attrs:[...h.querySelectorAll('*')].flatMap(x=>[...x.attributes].filter(a=>/^(data-|aria-|title$)/.test(a.name)).map(a=>a.name))}));assert.deepEqual(all,{ids:[],attrs:[]});return expected;}
async function coverage(s,run){const p=s.page,cdp=await s.context.newCDPSession(p);await cdp.send('Profiler.enable');await cdp.send('Profiler.startPreciseCoverage',{callCount:true,detailed:true});await run();const {result}=await cdp.send('Profiler.takePreciseCoverage');await cdp.send('Profiler.stopPreciseCoverage');await cdp.detach();const scripts=result.filter(x=>x.url.includes(ART)),counts={};for(const name of ['evaluate','analyze','assessPresentation']){const matches=scripts.flatMap(x=>x.functions).filter(x=>x.functionName===name);assert.ok(matches.length,'Coverage missing '+name);counts[name]=matches.reduce((n,f)=>n+f.ranges[0].count,0);}return counts;}
async function processId(s){const c=await s.context.browser().newBrowserCDPSession(),r=await c.send('SystemInfo.getProcessInfo');await c.detach();const pid=r.processInfo.find(x=>x.type==='browser').id;assert.ok(pid>0);return pid;}
async function cold(s){const before=await processId(s);await bounded(s.context.close(),10000);s.context=null;let gone=false;for(let i=0;i<100;i++){try{process.kill(before,0);}catch(e){if(e.code!=='ESRCH')throw e;gone=true;break;}await new Promise(resolve=>setTimeout(resolve,50));}assert.ok(gone,'Prior browser process survived close');s.offline=true;s.page=await s.start();await s.context.setOffline(true);const after=await processId(s);assert.notEqual(before,after);await normal(s.page,s);return {oldPid:before,newPid:after,priorProcessExited:true};}
async function rejected(s,r,worker=r.worker){publish(s,r);s.current=worker;const prior=await s.page.evaluateHandle(()=>navigator.serviceWorker.controller);const state=await s.page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('No failed install witness')),30000);r.addEventListener('updatefound',()=>{const w=r.installing;w.addEventListener('statechange',()=>{if(w.state==='redundant'||w.state==='installed'){clearTimeout(timer);resolve(w.state);}});},{once:true});r.update().catch(reject);});});assert.equal(state,'redundant');assert.equal(await s.page.evaluate(old=>navigator.serviceWorker.controller===old,prior),true);await prior.dispose();assert.equal(await s.page.evaluate(name=>caches.has(name),r.cacheName),false);return {state,cacheRemoved:true,priorControllerPreserved:true};}
async function sub(t,name,fn){await t.test(name,{timeout:180000},async()=>{try{await fn();cases++;}catch(e){failures.push({name,error:e.message});throw e;}});}
async function using(source,fn){const s=await environment(source);try{return await fn(s);}finally{await dispose(s);}}
async function firstInstall(s,r,{worker=r.worker,capturePuts=false}={}){
 if(capturePuts)await s.context.addInitScript(()=>{globalThis.__privatePutTrace=[];navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.privateCachePut)globalThis.__privatePutTrace.push(e.data.privateCachePut);});});
 publish(s,r);s.current=worker;const legacyApp=s.page.waitForResponse(x=>x.url()===s.origin+'/app.js');await normal(s.page,s);const response=await legacyApp;assert.equal(response.fromServiceWorker(),false);assert.equal(sha256(await response.body()),sha256(inputs.legacy.get('app.js')));assert.equal(await s.page.evaluate(()=>navigator.serviceWorker.controller),null);await s.page.evaluate(()=>navigator.serviceWorker.ready);await s.page.waitForFunction(()=>navigator.serviceWorker.getRegistration().then(r=>r.active?.state==='activated'));const sealed=await complete(s,r);
 if(capturePuts){await s.page.waitForFunction(n=>globalThis.__privatePutTrace.length===n,r.inventory.assets.length+1);s.putTrace=await s.page.evaluate(()=>globalThis.__privatePutTrace);}
 await normal(s.page,s);assert.equal(await s.page.evaluate(()=>Boolean(navigator.serviceWorker.controller)),true);return sealed;
}
async function noAnalytics(s){assert.equal(await s.page.locator('#analyticsHost').count(),0);const html=await s.page.content();for(const state of[mf3,mf4,empty])for(const c of oracle(state).components)assert.ok(!html.includes(c.text),'Unexpected approved text');}
async function exportState(s){await s.page.locator('[data-nav="data"]').click();const event=s.page.waitForEvent('download');await s.page.locator('#exportBtn').click();const stream=await(await event).createReadStream();assert.ok(stream);const chunks=[];for await(const chunk of stream)chunks.push(chunk);const value=JSON.parse(Buffer.concat(chunks).toString());await s.page.locator('[data-nav="home"]').click();return value;}
async function importState(s,source){await s.page.locator('[data-nav="data"]').click();await s.page.locator('#importFile').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(source))});await s.page.waitForFunction(({KEY,text})=>localStorage.getItem(KEY)===text,{KEY,text:JSON.stringify(source)});await s.page.locator('[data-nav="home"]').click();}
function quotaWorker(r,n){return Buffer.from(`let __privateQuotaN=0;const __privatePut=Cache.prototype.put;Cache.prototype.put=function(...a){return ++__privateQuotaN===${n}?Promise.reject(new DOMException('Private quota fault','QuotaExceededError')):__privatePut.apply(this,a);};\n`+r.worker.toString());}
function putObserverWorker(r){return Buffer.from(`let __privateObservedPutN=0;const __privateActualPut=Cache.prototype.put;const __privateSeal=new URL(${JSON.stringify(r.sealURL)},self.registration.scope).href;Cache.prototype.put=async function(request,response){const sequence=++__privateObservedPutN,url=String(request?.url||request),sealBefore=Boolean(await this.match(__privateSeal));await __privateActualPut.call(this,request,response);const sealAfter=Boolean(await this.match(__privateSeal)),witness={sequence,url,completed:true,sealBefore,sealAfter};for(const client of await self.clients.matchAll({includeUncontrolled:true}))client.postMessage({privateCachePut:witness});};\n`+r.worker.toString());}
const out=path.resolve(process.env.PHEISIRAETHA_2B4_OUTPUT);
const cli=JSON.parse(fs.readFileSync(path.join(out,'release-inventory.json')));
assert.equal(cli.releaseDigest,primary.releaseDigest);assert.deepEqual(cli.inventory,primary.inventory);
for(const[file,bytes]of primary.files)assert.deepEqual(fs.readFileSync(path.join(out,file)),bytes,'CLI overlay '+file);
assert.equal(fs.existsSync(path.join(EVID,'matrix.json')),false,'Fresh matrix output required');
const inventoryWitness={releaseDigest:primary.releaseDigest,cacheName:primary.cacheName,workerSha256:sha256(primary.worker)};
test('2B-4 private browser lifecycle qualification',{timeout:900000},async t=>{
 await sub(t,'COLD-00 never installed offline',()=>using(mf4,async s=>{s.offline=true;await s.context.setOffline(true);await assert.rejects(s.page.goto(s.origin+'/'));assert.equal(s.context.serviceWorkers().length,0);assert.equal(await s.page.locator('#analyticsHost').count(),0);row('COLD-00',{uninstalled:true,offlineNavigationRejected:true,workerCount:0});}));
 await sub(t,'INSTALL-01 exact CLI uncontrolled legacy SRI bootstrap',()=>using(mf4,async s=>{const sealed=await firstInstall(s,primary);assert.equal(await s.page.evaluate(()=>Object.hasOwn(globalThis,'PHEISIRAETHA_ANALYTICS_V1')),true);assert.deepEqual(await storage(s).then(x=>x.state),mf4);installWitness={...inventoryWitness,...sealed,initialLegacyExecutableSha256:sha256(inputs.legacy.get('app.js')),uncontrolledBootstrapPinned:true,controlledCandidateLoaded:true};}));
 await sub(t,'INSTALL-01 separate actual Cache.put seal-last observer',()=>using(mf4,async s=>{
  const worker=putObserverWorker(primary);await firstInstall(s,primary,{worker,capturePuts:true});const trace=s.putTrace,n=primary.inventory.assets.length;assert.equal(trace.length,n+1);
  for(let i=0;i<n;i++){assert.deepEqual(trace[i],{sequence:i+1,url:new URL(primary.cacheKey(primary.inventory.assets[i].url),s.origin+'/').href,completed:true,sealBefore:false,sealAfter:false});}
  assert.deepEqual(trace[n],{sequence:n+1,url:new URL(primary.sealURL,s.origin+'/').href,completed:true,sealBefore:false,sealAfter:true});assert.ok(installWitness,'Exact CLI installation witness missing');
  const proof={scope:'PRIVATE_CACHE_API_OBSERVER',instrumentedWorkerSha256:sha256(worker),originalWorkerSha256:sha256(primary.worker),assetCount:n,trace,sealWrittenLast:true};row('INSTALL-01',{...installWitness,sealLastProbe:proof});extras.push({id:'INSTALL-SEAL-LAST-PROBE',status:'PASS',witnesses:proof});
 }));
 await sub(t,'BOOTSTRAP-SRI-DENIAL valid but incorrect legacy JS',()=>using(mf4,async s=>{
  publish(s,primary);s.fault={url:'app.js',kind:'bootstrap'};const consoleMessages=[];s.page.on('console',m=>consoleMessages.push(m.text()));const response=s.page.waitForResponse(r=>r.url()===s.origin+'/app.js');await s.page.goto(s.origin+'/');assert.equal((await response).status(),200);await s.page.waitForFunction(()=>!document.body.classList.contains('is-launching'));
  const bad=Buffer.concat([inputs.legacy.get('app.js'),Buffer.from('\n;globalThis.__privateBootstrapCorruptionExecuted=true;\n')]),computed=Buffer.from(sha256(bad),'hex').toString('base64');assert.ok(consoleMessages.some(m=>/integrity/i.test(m)&&m.includes(computed)),'Browser computed SRI rejection witness missing');assert.equal(await s.page.evaluate(()=>Object.hasOwn(globalThis,'__privateBootstrapCorruptionExecuted')),false);assert.equal(await s.page.locator('#app').innerHTML(),'');assert.equal(s.context.serviceWorkers().length,0);await storage(s);
  extras.push({id:'BOOTSTRAP-SRI-DENIAL',status:'PASS',witnesses:{incorrectScriptSha256:sha256(bad),expectedLegacyScriptSha256:sha256(inputs.legacy.get('app.js')),browserComputedDigest:computed,scriptExecuted:false,workerCount:0,sriConsole:consoleMessages.filter(m=>/integrity/i.test(m))}});
 }));
 await sub(t,'OFF / mixed v16 clients / cache miss / upgrade / actual cold and warm',()=>using(mf4,async s=>{
  await legacy(s);const b=await s.context.newPage();await normal(b,s);const beforeB=await b.evaluateHandle(()=>navigator.serviceWorker.controller),w=await waiting(s,primary);const sealed=await complete(s,primary);
  assert.equal(await b.evaluate(old=>navigator.serviceWorker.controller===old,beforeB),true);assert.equal(await s.page.evaluate(()=>navigator.serviceWorker.getRegistration().then(r=>r.waiting.state)),'installed');row('MIX-01',{oldClientCount:2,candidateWaiting:true,establishedLegacy:s.legacyWitness,waitingWorker:s.waitingWitness,...sealed});
  assert.equal(await s.page.evaluate(async origin=>{const c=await caches.open('pheisiraetha-v16');return c.delete(origin+'/app.js');},s.origin),true);
  assert.equal(await s.page.evaluate(async origin=>Boolean(await caches.match(origin+'/app.js')),s.origin),false,'Candidate staging leaked a canonical legacy key');
  const response=s.page.waitForResponse(x=>x.url()===s.origin+'/app.js');await normal(s.page,s);assert.equal(sha256(await(await response).body()),sha256(inputs.legacy.get('app.js')));assert.equal(await b.evaluate(old=>navigator.serviceWorker.controller===old,beforeB),true);await beforeB.dispose();row('MIX-02',{legacyCacheMiss:true,candidateInvisibleToGlobalMatch:true,legacyAppSha256:sha256(inputs.legacy.get('app.js')),candidateStillWaiting:true});
  const alias=primary.inventory.assets.find(a=>a.url.startsWith('release-assets/app.')&&a.url.endsWith('.js')).url;assert.equal(alias,`release-assets/app.${inputs.sourceAppSha256}.js`);let actual;s.context.on('response',r=>{if(r.url()===s.origin+'/'+alias)actual=r;});await activate(s,w);assert.ok(actual);assert.equal(actual.fromServiceWorker(),true);assert.equal(sha256(await actual.body()),sha256(inputs.candidate.get('app.js')));row('UPGRADE-01',{oldClientsClosed:true,candidateAppSha256:sha256(await actual.body()),servedByController:true,...await complete(s,primary)});
  const counts=await coverage(s,()=>normal(s.page,s));assert.deepEqual(counts,{evaluate:0,analyze:0,assessPresentation:0});await noAnalytics(s);row('OFF-01',{counts,artifactLoaded:true,productionFlag:'OFF',ordinaryHomeUsable:true});
  const pids=await cold(s);assert.equal(await s.page.evaluate(()=>Object.hasOwn(globalThis,'PHEISIRAETHA_ANALYTICS_V1')),true);await noAnalytics(s);row('COLD-01',{...pids,newProcess:true,serverOfflineBeforeLaunch:true,...await complete(s,primary)});
  const warmCounts=await coverage(s,async()=>{await s.page.locator('[data-nav="history"]').click();await s.page.locator('[data-nav="home"]').click();});assert.deepEqual(warmCounts,{evaluate:0,analyze:0,assessPresentation:0});await noAnalytics(s);await normal(s.page,s);row('WARM-01',{offlineNavigationAndReload:true,counts:warmCounts,...await complete(s,primary)});
  const persisted=await storage(s);assert.deepEqual(persisted.state,mf4);assert.deepEqual(await exportState(s),mf4);row('STORE-01',{keys:persisted.keys,indexedDB:persisted.databases,exportEqualsBusinessState:true,onlyStaticReleaseCacheEntries:true,...await complete(s,primary)});
 }));
 const fetchResults=[];
 for(const kind of['404','500','redirect','interrupt','opaque'])await sub(t,'FETCH-01 '+kind,()=>using(mf4,async s=>{
  await legacy(s);const r=release();let worker=r.worker,foreign;
  if(kind==='opaque'){
   foreign=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/javascript'});res.end(artifact);});await new Promise(resolve=>foreign.listen(0,'127.0.0.1',resolve));const foreignURL='http://127.0.0.1:'+foreign.address().port+'/opaque';
   await s.page.evaluate(()=>{globalThis.__privateOpaqueEvidence=null;navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.privateOpaque)globalThis.__privateOpaqueEvidence=e.data.privateOpaque;});});
   worker=Buffer.from(`const __privateFetch=self.fetch.bind(self);self.fetch=(...a)=>String(a[0]?.url||a[0]).includes(${JSON.stringify(ART)})?__privateFetch(${JSON.stringify(foreignURL)},{mode:'no-cors'}).then(async r=>{for(const c of await self.clients.matchAll({includeUncontrolled:true}))c.postMessage({privateOpaque:r.type});return r;}):__privateFetch(...a);\n`+worker.toString());
  }else s.fault={url:ART,kind};
  try{const result=await rejected(s,r,worker);if(kind==='opaque'){await s.page.waitForFunction(()=>globalThis.__privateOpaqueEvidence==='opaque');result.observedType='opaque';}s.fault=null;s.offline=true;await s.context.setOffline(true);await normal(s.page,s);await noAnalytics(s);await storage(s);fetchResults.push({kind,...result,priorReleaseOfflineUsable:true});}finally{if(foreign)await closeServer(foreign);}
 }));
 if(fetchResults.length===5)row('FETCH-01',{variants:fetchResults});
 const hashResults=[];for(const kind of['hash','size'])await sub(t,'HASH-01 '+kind,()=>using(mf4,async s=>{await legacy(s);const r=release();s.fault={url:ART,kind};const result=await rejected(s,r);s.fault=null;s.offline=true;await s.context.setOffline(true);await normal(s.page,s);await storage(s);hashResults.push({kind,...result,priorReleaseOfflineUsable:true});}));if(hashResults.length===2)row('HASH-01',{variants:hashResults});
 const quotaResults=[];for(const at of[1,4,primary.inventory.assets.length+1])await sub(t,'QUOTA-01 put '+at,()=>using(mf4,async s=>{await legacy(s);const r=release();assert.equal(r.inventory.assets.length,primary.inventory.assets.length);const result=await rejected(s,r,quotaWorker(r,at));s.offline=true;await s.context.setOffline(true);await normal(s.page,s);await storage(s);quotaResults.push({injectedPut:at,assetCount:r.inventory.assets.length,sealPutRejected:at===r.inventory.assets.length+1,...result,priorReleaseOfflineUsable:true});}));if(quotaResults.length===3){assert.ok(quotaResults.some(x=>x.sealPutRejected));row('QUOTA-01',{variants:quotaResults});}
 await sub(t,'DIGEST-01 altered pinned provenance',()=>using(mf4,async s=>{await legacy(s);const r=release(),original=r.worker.toString();assert.ok(original.includes('safety-registry-v1'));const tampered=Buffer.from(original.replace('safety-registry-v1','safety-registry-v0'));assert.notEqual(sha256(tampered),sha256(r.worker));const result=await rejected(s,r,tampered);s.offline=true;await s.context.setOffline(true);await normal(s.page,s);await storage(s);row('DIGEST-01',{tamperedProvenance:'registryVersion',releaseDigestNotRecomputed:true,...result,priorReleaseOfflineUsable:true});}));
 const cacheResults=[];for(const kind of['missing','corrupt'])await sub(t,'CACHE-01 '+kind,()=>using(mf4,async s=>{await firstInstall(s,primary);await s.page.evaluate(async({name,key,kind})=>{const c=await caches.open(name);if(kind==='missing'){if(!await c.delete(new URL(key,location.origin+'/')))throw Error('Artifact was not cached');}else await c.put(new URL(key,location.origin+'/'),new Response('private wrong artifact bytes',{headers:{'Content-Type':'text/javascript'}}));},{name:primary.cacheName,key:primary.cacheKey(ART),kind});s.offline=true;await s.context.setOffline(true);const response=s.page.waitForResponse(r=>r.url()===s.origin+'/'+ART);await normal(s.page,s);assert.ok((await response).status()>=400,'Unverified cached artifact served successfully');assert.equal(await s.page.evaluate(()=>Object.hasOwn(globalThis,'PHEISIRAETHA_ANALYTICS_V1')),false);await noAnalytics(s);await storage(s);cacheResults.push({kind,rejectedResponseStatus:(await response).status(),ordinaryOffHomeUsable:true,noArtifactNamespace:true});}));if(cacheResults.length===2)row('CACHE-01',{variants:cacheResults});
 for(const[id,source,count]of[['ON-VALID-5',mf3,5],['ON-VALID-9',mf4,9],['ON-VALID-FALLBACK',empty,1]])await sub(t,id,()=>using(source,async s=>{const r=release(true);await firstInstall(s,r);const counts=await coverage(s,()=>normal(s.page,s));for(const n of Object.values(counts))assert.ok(n>0,'Missing positive coverage');assert.equal((await analytics(s.page,source)).components.length,count);const pids=await cold(s);await analytics(s.page,source);await s.page.locator('[data-nav="history"]').click();await s.page.locator('[data-nav="home"]').click();await analytics(s.page,source);assert.deepEqual((await storage(s)).state,source);assert.deepEqual(await exportState(s),source);const witness={componentCount:count,counts,...pids,coldAndWarmOffline:true,cache:await complete(s,r)};
  if(id==='ON-VALID-5'){const old=await s.page.locator(HOST).elementHandle();await importState(s,mf4);assert.equal(await old.evaluate(x=>x.isConnected),false);assert.equal((await analytics(s.page,mf4)).components.length,9);assert.deepEqual((await storage(s)).state,mf4);assert.deepEqual(await exportState(s),mf4);witness.realAcceptedImportRecomputed5To9=true;}
  extras.push({id,status:'PASS',witnesses:witness});
 }));
 const onFailures=[];
 for(const kind of['namespace','malformedDTO','missingArtifact'])await sub(t,'ON-01 '+kind,()=>using(mf4,async s=>{const r=release(true);await firstInstall(s,r);await analytics(s.page,mf4);
  if(kind==='namespace'){await s.context.addInitScript(()=>Object.defineProperty(globalThis,'PHEISIRAETHA_ANALYTICS_V1',{value:Object.freeze({}),enumerable:true,writable:false,configurable:false}));await normal(s.page,s);}
  else if(kind==='malformedDTO'){await s.page.evaluate(()=>{const original=Object.getOwnPropertyDescriptors;Object.getOwnPropertyDescriptors=function(value){const descriptors=original(value);if(descriptors.dtoVersion?.value==='pheisiraetha-render-v1')descriptors.dtoVersion={...descriptors.dtoVersion,value:'private-invalid-render-dto'};return descriptors;};});await s.page.locator('[data-nav="history"]').click();await s.page.locator('[data-nav="home"]').click();}
  else{await s.page.evaluate(async({cache,key})=>{const c=await caches.open(cache);if(!await c.delete(new URL(key,location.origin+'/')))throw Error('Missing artifact cache fixture');},{cache:r.cacheName,key:r.cacheKey(ART)});s.offline=true;await s.context.setOffline(true);await normal(s.page,s);}
  await noAnalytics(s);assert.equal(await s.page.locator('#startCheckin').isVisible(),true);assert.deepEqual((await storage(s)).state,mf4);onFailures.push({kind,priorAllowRemoved:true,ordinaryHomeUsable:true,genuineArtifactUnmodified:true,privateBoundaryFaultOnly:true});
 }));if(onFailures.length===3)row('ON-01',{variants:onFailures});
 await sub(t,'ROLLBACK-01 complete prior OFF release after private ON upgrade',()=>using(mf4,async s=>{await firstInstall(s,primary);const on=release(true),w=await waiting(s,on);await activate(s,w);await analytics(s.page,mf4);const rollback=rollbackRelease(primary,'rollback-01');assert.deepEqual(rollback.entry,primary.entry);for(const[url,bytes]of primary.assets)assert.deepEqual(rollback.assets.get(url),bytes);assert.notEqual(rollback.releaseDigest,primary.releaseDigest);assert.notEqual(rollback.cacheName,on.cacheName);const rw=await waiting(s,rollback);await activate(s,rw);const counts=await coverage(s,()=>normal(s.page,s));assert.deepEqual(counts,{evaluate:0,analyze:0,assessPresentation:0});await noAnalytics(s);await cold(s);await noAnalytics(s);assert.deepEqual((await storage(s)).state,mf4);assert.deepEqual(await exportState(s),mf4);row('ROLLBACK-01',{priorEntrySha256:sha256(primary.entry),rollbackEntrySha256:sha256(rollback.entry),freshCacheName:rollback.cacheName,priorAllowRemoved:true,businessStatePreserved:true,counts,cache:await complete(s,rollback)});}));
 assert.deepEqual(failures,[],'Failed browser cases');assert.equal(rows.size,16);assert.deepEqual([...rows.keys()].sort(),[...IDS].sort());assert.ok(cases>=16);assert.deepEqual(extras.map(x=>x.id).sort(),['BOOTSTRAP-SRI-DENIAL','INSTALL-SEAL-LAST-PROBE','ON-VALID-5','ON-VALID-9','ON-VALID-FALLBACK'].sort());assert.ok(extras.every(x=>x.status==='PASS'));assert.equal(git('status','--porcelain'),initialGit);const finalInputs=readInputs(ROOT);assert.equal(finalInputs.frozenSourceTreeSha256,inputs.frozenSourceTreeSha256);assert.equal(finalInputs.sourceAppSha256,inputs.sourceAppSha256);const browserAfter=sha256(fs.readFileSync(browserPath));assert.equal(browserAfter,browserBefore);
 const report={status:'PASS',candidateCommit:git('rev-parse','HEAD'),releaseDigest:primary.releaseDigest,rows:IDS.map(id=>rows.get(id)),extras,skipped:0,todo:0,productionOFF:true,frozenUnchanged:true,browser:{path:browserPath,version:browserVersion,sha256Before:browserBefore,sha256After:browserAfter},tests:cases};fs.writeFileSync(path.join(EVID,'matrix.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,rows:report.rows.length,tests:cases,releaseDigest:report.releaseDigest}));
});
