'use strict';
// Private qualification only: no deployment or source flag changes.
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {createServer}=require('node:http'),{execFileSync}=require('node:child_process');
const {readInputs,sha256,canonical}=require('./build.cjs');
const {createStagedRelease,createStagedPair,rollbackStagedRelease,verifyStagedRelease,describeProposal}=require('./public-proposal.cjs');
const ROOT=path.resolve(__dirname,'..'),MAIN='255a5d9d27461dcacaebc1bc80ab322dd54b4de8',S3='7e583ac695be2b213d25591deab430664e682988';
const MOUNT='/pheisiraetha-app/',ART='browser-packaging/artifacts/analytics-v1.f1f975900faaa64649bcef42412c1856543c8716711d4119df9b964f4bf8c824.js';
const KEY='pheisiraetha_v01',LANG='pheisiraetha_language_v01',ONBOARD='pheisiraetha_onboarding_v01',HOST='#app > .shell > main > #analyticsHost';
const IDS=['PP-BUILD-01','PP-BOOTSTRAP-OFF','PP-HARDENING-01','PP-MIX-OFF','PP-MIX-ON','PP-ON-5','PP-ON-9','PP-FALLBACK','PP-IMPORT-01','PP-INSTALL-FAIL','PP-ROLLBACK-01'];
const ZERO={evaluate:0,analyze:0,assessPresentation:0},rows=new Map(),failures=[];
function git(...args){const env={...process.env};for(const key of Object.keys(env))if(key.startsWith('GIT_')||key==='NODE_OPTIONS')delete env[key];return execFileSync('git',['--no-optional-locks','-c','core.fsmonitor=false','-C',ROOT,...args],{env:{...env,GIT_NO_REPLACE_OBJECTS:'1',GIT_OPTIONAL_LOCKS:'0'},maxBuffer:64*1024*1024});}
const initialGit=git('status','--porcelain').toString();assert.equal(initialGit,'');
assert.equal(process.platform,'linux');assert.equal(process.version,'v24.19.0');assert.equal(require('playwright/package.json').version,'1.62.1');
const external=fs.realpathSync(require.resolve('playwright/package.json'));assert.ok(!external.startsWith(ROOT+path.sep),'External Playwright required');
const chromium=require('playwright').chromium,browserPath=fs.realpathSync(process.env.LEGACY_DOM_CHROMIUM_EXECUTABLE_PATH),browserBefore=sha256(fs.readFileSync(browserPath));
const inputs=readInputs(ROOT),pair=createStagedPair(inputs,{offGeneration:'offline-candidate-11',onGeneration:'offline-candidate-12'}),off=pair.off,on=pair.on;
const sourceApp=inputs.candidate.get('app.js'),artifact=inputs.candidate.get(ART),legacyWorker=git('show',MAIN+':sw.js');
assert.equal(sha256(legacyWorker),inputs.legacyWorkerSha256);assert.equal(git('rev-parse',S3+':app.js').toString().trim(),'23a293db0bad74bbf565ae7780ba6ab249ca0a95');
const fixtures=require(path.join(ROOT,'browser-packaging/runtime-core/fixtures.cjs')),labels=Array(10).fill('Calm / contentment');
const mf3=fixtures.reflection(labels,'B4',true),mf4=fixtures.fixture(1,labels),empty=fixtures.fixture(0,labels);
function oracle(source){const realm=vm.createContext({input:JSON.stringify(source)});vm.runInContext(artifact.toString(),realm,{timeout:10000});return JSON.parse(vm.runInContext('JSON.stringify(PHEISIRAETHA_ANALYTICS_V1.evaluate(JSON.parse(input)))',realm,{timeout:10000}));}
assert.equal(oracle(mf3).components.length,5);assert.equal(oracle(mf4).components.length,9);assert.equal(oracle(empty).mode,'FALLBACK_ONLY');
const output=path.resolve(process.env.PHEISIRAETHA_PUBLIC_OUTPUT),cli=JSON.parse(fs.readFileSync(path.join(output,'proposal-evidence.json')));
let cases=0,browserVersion;
function outside(directory){const rel=path.relative(ROOT,directory);assert.ok(rel==='..'||rel.startsWith('..'+path.sep)||path.isAbsolute(rel),'External output directory required');}
outside(fs.realpathSync(output));
const evidence=process.env.PHEISIRAETHA_PUBLIC_EVIDENCE&&path.resolve(process.env.PHEISIRAETHA_PUBLIC_EVIDENCE);
if(evidence){outside(evidence);fs.mkdirSync(evidence,{recursive:true});assert.equal(fs.existsSync(path.join(evidence,'public-proposal-matrix.json')),false,'Fresh evidence directory required');}
async function bounded(p,ms=30000){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Private proposal lifecycle timeout')),ms);})]);}finally{clearTimeout(timer);}}
function row(id,witnesses){assert.ok(IDS.includes(id));assert.ok(!rows.has(id));assert.ok(witnesses&&Object.keys(witnesses).length);rows.set(id,{id,status:'PASS',witnesses});}
function mime(file){return file==='__seed'||file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.webmanifest')?'application/manifest+json':file.endsWith('.png')?'image/png':file.endsWith('.jpg')?'image/jpeg':'application/octet-stream';}
async function closeServer(server){server.closeAllConnections();await bounded(new Promise(resolve=>server.close(resolve)),5000);}
async function dispose(s){try{if(s.context)await bounded(s.context.close(),10000);}finally{await closeServer(s.server);}}
async function environment(source=mf4){
 const s={current:legacyWorker,bootstrap:null,aliases:new Map(),fault:null,offline:false,requests:[],context:null,profile:fs.mkdtempSync(path.join(os.tmpdir(),'pheisiraetha-public-proposal-'))};
 s.server=createServer((req,res)=>{const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith(MOUNT)){res.writeHead(404);res.end('Outside project scope');return;}
  const physical=u.pathname.slice(MOUNT.length)||'index.html',key=u.pathname.slice(MOUNT.length)+(u.search||'');let bytes;
  if(physical==='sw.js')bytes=s.current;else if(physical==='__seed')bytes=Buffer.from('<!doctype html><title>Private seed</title>');else if(physical==='index.html'&&s.bootstrap)bytes=s.bootstrap;else if(inputs.legacy.has(physical))bytes=inputs.legacy.get(physical);else bytes=s.aliases.get(key)||s.aliases.get(physical);
  const fault=s.fault&&s.fault.url===key?s.fault.kind:null;s.requests.push({url:key,method:req.method,offline:s.offline,fault,sha256:bytes&&sha256(bytes)});
  if(s.offline){res.destroy();return;}if(!bytes||fault==='404'){res.writeHead(404);res.end('Private unavailable asset');return;}
  res.writeHead(200,{'Content-Type':mime(physical),'Cache-Control':'no-store','Service-Worker-Allowed':MOUNT});res.end(bytes);
 });
 await new Promise(resolve=>s.server.listen(0,'127.0.0.1',resolve));s.origin='http://127.0.0.1:'+s.server.address().port;s.scopeURL=s.origin+MOUNT;
 s.start=async()=>{s.context=await chromium.launchPersistentContext(s.profile,{headless:true,executablePath:browserPath,serviceWorkers:'allow'});browserVersion=s.context.browser().version();s.context.on('page',p=>p.on('dialog',d=>d.accept()));for(const p of s.context.pages())p.on('dialog',d=>d.accept());return s.context.pages()[0]||s.context.newPage();};
 try{s.page=await s.start();await s.page.goto(s.scopeURL+'__seed');await s.page.evaluate(({source,KEY,LANG,ONBOARD})=>{localStorage.setItem(KEY,JSON.stringify(source));localStorage.setItem(LANG,'en');localStorage.setItem(ONBOARD,'1');},{source,KEY,LANG,ONBOARD});return s;}catch(error){await dispose(s);throw error;}
}
async function using(source,fn){const s=await environment(source);try{return await fn(s);}finally{await dispose(s);}}
async function normal(p,s,file=''){const response=await p.goto(s.scopeURL+file);await p.waitForFunction(()=>!document.body.classList.contains('is-launching'));assert.equal(await p.locator('#startCheckin').isVisible(),true);return response;}
async function registrationState(p,kind){return bounded(p.evaluate(async kind=>{const deadline=Date.now()+30000;for(;;){const r=await navigator.serviceWorker.getRegistration(),worker=kind==='waiting'?r?.waiting:r?.active,wanted=kind==='waiting'?'installed':'activated';if(worker?.state===wanted)return {kind,state:worker.state,scriptURL:worker.scriptURL,scope:r.scope};if(Date.now()>=deadline)throw Error('Registration state timeout '+kind);await new Promise(resolve=>setTimeout(resolve,20));}},kind),31000);}
function publish(s,r){verifyStagedRelease(r);assert.deepEqual(r.files.get('index.html'),r.bootstrap);assert.deepEqual(r.assets.get('index.html'),r.bootstrap);assert.deepEqual(r.assets.get(r.bootstrapAppURL),sourceApp);for(const file of inputs.legacy.keys())if(file!=='index.html')assert.deepEqual(r.files.get(file),inputs.legacy.get(file),'Canonical legacy '+file);s.bootstrap=r.bootstrap;for(const[url,bytes]of r.assets)s.aliases.set(url,bytes);s.current=r.worker;}
async function workerIdentity(w,s,r){const actual=await w.evaluate(()=>({releaseDigest:CONFIG.releaseDigest,cacheName:CONFIG.cacheName,entryURL:CONFIG.inventory.entryURL,scope:self.registration.scope}));assert.deepEqual(actual,{releaseDigest:r.releaseDigest,cacheName:r.cacheName,entryURL:r.entryURL,scope:s.scopeURL});return actual;}
async function waiting(s,r){const event=s.context.waitForEvent('serviceworker',{timeout:30000});publish(s,r);await s.page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration();await registration.update();});const w=await event,settled=await registrationState(s.page,'waiting');assert.equal(settled.scope,s.scopeURL);return {worker:w,witness:{...await workerIdentity(w,s,r),settled}};}
async function activate(s,waitingWorker){const w=waitingWorker.worker||waitingWorker;assert.equal(await bounded(w.evaluate(()=>{globalThis.__privateActivationObserved=false;self.addEventListener('activate',()=>{globalThis.__privateActivationObserved=true;},{once:true});return true;})),true);for(const p of s.context.pages())await bounded(p.close());await bounded(w.evaluate(()=>new Promise((resolve,reject)=>{const deadline=Date.now()+30000,poll=()=>{if(self.registration.active?.state==='activated'&&globalThis.__privateActivationObserved===true)return resolve(true);if(Date.now()>=deadline)return reject(Error('Natural activation not observed'));setTimeout(poll,20);};poll();})),31000);s.page=await s.context.newPage();return normal(s.page,s);}
async function complete(s,r){return s.page.evaluate(async({cacheName,sealURL,prefix,assets,digest,scope})=>{const names=await caches.keys(),registration=await navigator.serviceWorker.getRegistration(),seal=new URL(sealURL,scope).href,state={names,cacheName,scope:registration?.scope,active:registration?.active?.state,waiting:registration?.waiting?.state};if(!names.includes(cacheName))throw Error('Candidate cache absent '+JSON.stringify(state));const cache=await caches.open(cacheName),marker=await cache.match(seal),body=marker?await marker.text():null,keys=await cache.keys();if(!marker||marker.status!==200||body!==JSON.stringify({releaseDigest:digest,assetCount:assets.length,complete:true}))throw Error('Exact seal mismatch '+JSON.stringify({...state,body,keys:keys.map(k=>k.url)}));if(keys.length!==assets.length+1)throw Error('Cache cardinality mismatch');for(const a of assets){const response=await cache.match(new URL(prefix+encodeURIComponent(a.url),scope));if(!response)throw Error('Missing asset '+a.url);const bytes=await response.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(bytes.byteLength!==a.sizeBytes||hash!==a.sha256)throw Error('Asset integrity '+a.url);}return {cacheName,sealURL:seal,entryCount:keys.length,exactSeal:true,allAssetHashesVerified:true};},{cacheName:r.cacheName,sealURL:r.sealURL,prefix:r.cacheKeyPrefix,assets:r.inventory.assets,digest:r.releaseDigest,scope:s.scopeURL});}
async function legacy(s){await normal(s.page,s);await s.page.waitForFunction(()=>Boolean(navigator.serviceWorker.controller));const established=await registrationState(s.page,'active');assert.equal(established.scope,s.scopeURL);const urls=['./','index.html','app.css','launch.js','app.js','locales.js','manifest.webmanifest?v=07','launch-screen.jpg?v=15','icon-192.png?v=07','icon-512.png?v=07','icon-maskable-192.png?v=07','icon-maskable-512.png?v=07'];const assets=urls.map(url=>{const b=inputs.legacy.get(url==='./'?'index.html':url.split('?')[0]);return {url,sha256:sha256(b),sizeBytes:b.length};});return s.page.evaluate(async({assets,scope})=>{const names=await caches.keys();if(!names.includes('pheisiraetha-v16'))throw Error('Established legacy cache missing');const cache=await caches.open('pheisiraetha-v16');for(const a of assets){const r=await cache.match(new URL(a.url,scope));if(!r)throw Error('Legacy asset missing '+a.url);const b=await r.arrayBuffer(),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');if(b.byteLength!==a.sizeBytes||hash!==a.sha256)throw Error('Legacy asset bytes '+a.url);}const r=await navigator.serviceWorker.getRegistration();return {cache:'pheisiraetha-v16',verifiedAssets:assets.length,state:r.active.state,scope:r.scope,controller:navigator.serviceWorker.controller.scriptURL};},{assets,scope:s.scopeURL});}
async function coverage(s,run){const cdp=await s.context.newCDPSession(s.page);try{await cdp.send('Profiler.enable');await cdp.send('Profiler.startPreciseCoverage',{callCount:true,detailed:true});await run();const {result}=await cdp.send('Profiler.takePreciseCoverage'),scripts=result.filter(x=>x.url===s.scopeURL+ART),counts={};for(const name of Object.keys(ZERO)){const matches=scripts.flatMap(x=>x.functions).filter(f=>f.functionName===name);assert.ok(matches.length,'Missing actual artifact coverage '+name);counts[name]=matches.reduce((n,f)=>n+f.ranges[0].count,0);}return counts;}finally{await cdp.send('Profiler.stopPreciseCoverage').catch(()=>{});await cdp.detach();}}
async function noAnalytics(s){assert.equal(await s.page.locator('#analyticsHost').count(),0);const content=await s.page.content();for(const state of [mf3,mf4,empty])for(const c of oracle(state).components)assert.ok(!content.includes(c.text),'Approved analytics outside OFF boundary');}
async function analytics(p,source){const expected=oracle(source),host=p.locator(HOST);assert.equal(await host.count(),1);assert.deepEqual(await host.locator('section.card > p').allTextContents(),expected.components.map(c=>c.text));assert.equal(await host.locator('section.card').getAttribute('lang'),'en');assert.equal(await host.locator('section.card').getAttribute('dir'),'ltr');const forbidden=await host.evaluate(h=>({ids:[...h.querySelectorAll('[id]')].map(x=>x.id),attrs:[...h.querySelectorAll('*')].flatMap(x=>[...x.attributes].filter(a=>/^(data-|aria-|title$)/.test(a.name)).map(a=>a.name))}));assert.deepEqual(forbidden,{ids:[],attrs:[]});return expected;}
async function storage(s,source){const value=await s.page.evaluate(async({KEY,LANG,ONBOARD})=>({keys:Object.keys(localStorage).sort(),state:JSON.parse(localStorage.getItem(KEY)),databases:(await indexedDB.databases()).map(x=>x.name)}),{KEY,LANG,ONBOARD});assert.deepEqual(value.keys,[KEY,LANG,ONBOARD].sort());assert.deepEqual(value.databases,[]);if(source)assert.deepEqual(value.state,source);assert.ok(s.requests.every(x=>x.method==='GET'));assert.ok(s.requests.every(x=>!/(synthetic-core|Synthetic%20|private-injection)/.test(x.url)));return value;}
async function exportState(s){await s.page.locator('[data-nav="data"]').click();const event=s.page.waitForEvent('download');await s.page.locator('#exportBtn').click();const stream=await(await event).createReadStream();assert.ok(stream);const chunks=[];for await(const chunk of stream)chunks.push(chunk);const value=JSON.parse(Buffer.concat(chunks).toString());await s.page.locator('[data-nav="home"]').click();return value;}
async function importState(s,source){await s.page.locator('[data-nav="data"]').click();await s.page.locator('#importFile').setInputFiles({name:'private-state.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(source))});await s.page.waitForFunction(({KEY,text})=>localStorage.getItem(KEY)===text,{KEY,text:JSON.stringify(source)});await s.page.locator('[data-nav="home"]').click();}
async function processId(s){const cdp=await s.context.browser().newBrowserCDPSession();try{const info=await cdp.send('SystemInfo.getProcessInfo'),browser=info.processInfo.find(p=>p.type==='browser');assert.ok(browser&&Number.isSafeInteger(browser.id)&&browser.id>0);return browser.id;}finally{await cdp.detach();}}
async function cold(s){const oldPid=await processId(s);await bounded(s.context.close(),10000);s.context=null;let exited=false;for(let i=0;i<100;i++){try{process.kill(oldPid,0);}catch(error){if(error.code!=='ESRCH')throw error;exited=true;break;}await new Promise(resolve=>setTimeout(resolve,50));}assert.ok(exited,'Previous browser process still exists');s.offline=true;s.page=await s.start();await s.context.setOffline(true);const newPid=await processId(s);assert.notEqual(oldPid,newPid);await normal(s.page,s);return {oldPid,newPid,priorProcessExited:true,serverOfflineBeforeNewProcess:true};}
async function sri(s,r){const elements=await s.page.evaluate(()=>[...document.querySelectorAll('script[src],link[rel="stylesheet"]')].map(e=>({url:e.getAttribute('src')||e.getAttribute('href'),integrity:e.getAttribute('integrity'),crossorigin:e.getAttribute('crossorigin')})));assert.equal(elements.length,5);for(const e of elements){const bytes=r.assets.get(e.url);assert.ok(bytes,'Uninventoried bootstrap executable '+e.url);assert.equal(e.integrity,'sha256-'+Buffer.from(sha256(bytes),'hex').toString('base64'));assert.equal(e.crossorigin,'anonymous');assert.equal(new URL(e.url,s.scopeURL).pathname.startsWith(MOUNT),true);}assert.ok(elements.some(e=>e.url===r.bootstrapAppURL));return elements;}
async function initial(s,r){publish(s,r);const app=s.page.waitForResponse(x=>x.url()===s.scopeURL+r.bootstrapAppURL);let navigation;const counts=await coverage(s,async()=>{navigation=await normal(s.page,s);});assert.deepEqual(counts,ZERO);assert.equal(navigation.fromServiceWorker(),false);assert.equal(sha256(await navigation.body()),sha256(r.bootstrap));const response=await app;assert.equal(response.fromServiceWorker(),false);assert.deepEqual(await response.body(),sourceApp);assert.equal(await s.page.evaluate(()=>navigator.serviceWorker.controller),null);await noAnalytics(s);const attributes=await sri(s,r);await bounded(s.page.evaluate(()=>navigator.serviceWorker.ready),31000);const active=await registrationState(s.page,'active');assert.equal(active.scope,s.scopeURL);return {scope:s.scopeURL,initialController:null,bootstrapSha256:sha256(r.bootstrap),bootstrapAppSha256:sha256(sourceApp),counts,sri:attributes,cache:await complete(s,r)};}
async function selected(s,r){const response=await normal(s.page,s);assert.equal(response.fromServiceWorker(),true);assert.deepEqual(await response.body(),r.entry);assert.equal(await s.page.evaluate(()=>navigator.serviceWorker.getRegistration().then(r=>r.scope)),s.scopeURL);assert.equal(await s.page.evaluate(()=>Boolean(navigator.serviceWorker.controller)),true);return response;}
async function oldControllerStillActive(s){assert.equal(await s.page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return navigator.serviceWorker.controller===r.active&&r.active.state==='activated'&&r.waiting?.state==='installed';}),true);}
async function sub(t,id,fn){await t.test(id,{timeout:240000},async()=>{try{const witness=await fn();row(id,witness);cases++;}catch(error){failures.push({id,error:error.message});throw error;}});}

test('Private hardened public proposal qualification',{timeout:1200000},async t=>{
 await sub(t,'PP-BUILD-01',async()=>{
  verifyStagedRelease(off);verifyStagedRelease(on);
  const again=createStagedPair(inputs,{offGeneration:'offline-candidate-11',onGeneration:'offline-candidate-12'});
  assert.equal(cli.status,'STAGED_UNQUALIFIED');assert.equal(cli.deploymentPerformed,false);assert.equal(cli.expectedMountPath,MOUNT);assert.equal(cli.integrationCommit,S3);assert.equal(cli.sourceCommit,git('rev-parse','HEAD').toString().trim());assert.equal(cli.proposalModuleSha256,sha256(fs.readFileSync(path.join(__dirname,'public-proposal.cjs'))));
  for(const [name,r]of [['off',off],['on',on]]){
   assert.deepEqual(cli[name],describeProposal(r));assert.equal(r.releaseDigest,sha256(canonical(r.inventory)));assert.deepEqual(r.worker,again[name].worker);assert.deepEqual(r.entry,again[name].entry);assert.deepEqual(r.bootstrap,off.entry);assert.deepEqual(r.assets.get(r.bootstrapAppURL),sourceApp);assert.match(sourceApp.toString(),/const ANALYTICS_ENABLED = false;/);assert.equal(r.files.size,again[name].files.size);assert.equal(r.assets.size,again[name].assets.size);
   for(const[file,bytes]of r.files){assert.deepEqual(bytes,again[name].files.get(file));assert.deepEqual(fs.readFileSync(path.join(output,name,file)),bytes,'Exact CLI '+name+'/'+file);}
   for(const[url,bytes]of r.assets)assert.deepEqual(bytes,again[name].assets.get(url));assert.deepEqual(r.assets.get(ART),artifact);for(const file of inputs.legacy.keys())if(file!=='index.html')assert.deepEqual(r.files.get(file),inputs.legacy.get(file));
  }
  assert.equal(off.inventory.proposal.activeMode,'OFF');assert.equal(on.inventory.proposal.activeMode,'ON');assert.notEqual(off.releaseDigest,on.releaseDigest);assert.notEqual(off.cacheName,on.cacheName);assert.deepEqual(off.bootstrap,on.bootstrap);
  return {sourceCommit:cli.sourceCommit,sourceFlag:'OFF',integrationCommit:S3,scope:MOUNT,deterministic:true,exactCLI:true,off:describeProposal(off),on:describeProposal(on)};
 });
 await sub(t,'PP-BOOTSTRAP-OFF',()=>using(mf4,async s=>{const witness=await initial(s,on);await storage(s,mf4);await selected(s,on);await analytics(s.page,mf4);return {...witness,selectedMode:'ON',naturalInitialActivation:true,bootstrapMode:'OFF',businessStateUnchanged:true};}));
 await sub(t,'PP-HARDENING-01',async()=>{
  const source=structuredClone(mf4),payload='<img data-private-injection src="data:image/png,broken" onerror="globalThis.__privateRatingExecuted=true">';
  for(const[container,key]of [['oop','achievement'],['iep','desire'],['iep','mental'],['iep','practical']])source.intent.cycles[0][container][key]=payload;
  return using(source,async s=>{const bootstrap=await initial(s,off);for(const view of ['home','history','home']){await s.page.locator('[data-nav="'+view+'"]').click();assert.equal(await s.page.locator('[data-private-injection]').count(),0);assert.equal(await s.page.evaluate(()=>globalThis.__privateRatingExecuted===true),false);assert.ok((await s.page.locator('#app').textContent()).includes(payload));await noAnalytics(s);await storage(s,source);}assert.deepEqual(await exportState(s),source);return {...bootstrap,maliciousRatingFields:4,homeAndHistoryInert:true,storedValuesUnchanged:true,exportUnchanged:true};});
 });
 for(const[mode,r]of [['OFF',off],['ON',on]])await sub(t,'PP-MIX-'+mode,()=>using(mf4,async s=>{
  const old=await legacy(s),b=await s.context.newPage();await normal(b,s);
  const beforeA=await s.page.evaluateHandle(()=>navigator.serviceWorker.controller),beforeB=await b.evaluateHandle(()=>navigator.serviceWorker.controller),candidate=await waiting(s,r),seal=await complete(s,r);
  assert.equal(await s.page.evaluate(h=>navigator.serviceWorker.controller===h,beforeA),true);assert.equal(await b.evaluate(h=>navigator.serviceWorker.controller===h,beforeB),true);await oldControllerStillActive(s);await beforeA.dispose();
  assert.equal(await s.page.evaluate(async scope=>{const c=await caches.open('pheisiraetha-v16');return c.delete(new URL('app.js',scope));},s.scopeURL),true);
  assert.equal(await s.page.evaluate(async scope=>Boolean(await caches.match(new URL('app.js',scope))),s.scopeURL),false);
  const legacyApp=s.page.waitForResponse(x=>x.url()===s.scopeURL+'app.js');await normal(s.page,s);assert.deepEqual(await(await legacyApp).body(),inputs.legacy.get('app.js'));await noAnalytics(s);await oldControllerStillActive(s);assert.equal(await b.evaluate(h=>navigator.serviceWorker.controller===h,beforeB),true);
  const bridge=[];
  for(const file of ['', 'index.html']){
   await s.page.evaluate(async({scope,file})=>{const c=await caches.open('pheisiraetha-v16');if(!await c.delete(new URL(file||'./',scope)))throw Error('Legacy document cache entry absent');},{scope:s.scopeURL,file});
   assert.equal(await s.page.evaluate(async({scope,url})=>Boolean(await caches.match(new URL(url,scope))),{scope:s.scopeURL,url:r.bootstrapAppURL}),false);
   const app=s.page.waitForResponse(x=>x.url()===s.scopeURL+r.bootstrapAppURL);let response;
   const bridgeCounts=await coverage(s,async()=>{response=await normal(s.page,s,file);});assert.deepEqual(bridgeCounts,ZERO);
   assert.deepEqual(await response.body(),r.bootstrap);assert.deepEqual(await(await app).body(),sourceApp);await noAnalytics(s);await oldControllerStillActive(s);assert.equal(await b.evaluate(h=>navigator.serviceWorker.controller===h,beforeB),true);assert.equal((await registrationState(s.page,'waiting')).state,'installed');
   bridge.push({document:file||'./',bootstrapSha256:sha256(await response.body()),appSha256:sha256(sourceApp),legacyControllerPreserved:true,counts:bridgeCounts,sri:await sri(s,r)});
  }
  await beforeB.dispose();const entry=await activate(s,candidate);assert.equal(entry.fromServiceWorker(),true);assert.deepEqual(await entry.body(),r.entry);
  const counts=await coverage(s,()=>normal(s.page,s));let offlineWitness=null;
  if(mode==='OFF'){
   assert.deepEqual(counts,ZERO);await noAnalytics(s);const processes=await cold(s);
   const warmCounts=await coverage(s,async()=>{await normal(s.page,s);await s.page.locator('[data-nav="history"]').click();await s.page.locator('[data-nav="home"]').click();});assert.deepEqual(warmCounts,ZERO);await noAnalytics(s);offlineWitness={...processes,warmCounts,coldWarmOffline:true};
  }else{for(const v of Object.values(counts))assert.ok(v>0);await analytics(s.page,mf4);}
  await storage(s,mf4);assert.deepEqual(await exportState(s),mf4);
  return {scope:s.scopeURL,oldClients:2,establishedV16:old,waiting:candidate.witness,cache:seal,canonicalAppCacheMissSha256:sha256(inputs.legacy.get('app.js')),privateCacheKeysInvisible:true,documentBridges:bridge,naturalActivation:true,selectedMode:mode,selectedEntrySha256:sha256(r.entry),counts,offline:offlineWitness};
 }));
 for(const[id,source,count]of [['PP-ON-5',mf3,5],['PP-ON-9',mf4,9],['PP-FALLBACK',empty,1]])await sub(t,id,()=>using(source,async s=>{
  await initial(s,on);await selected(s,on);const counts=await coverage(s,()=>normal(s.page,s));for(const n of Object.values(counts))assert.ok(n>0);const dto=await analytics(s.page,source);assert.equal(dto.components.length,count);
  if(id==='PP-FALLBACK'){assert.equal(dto.mode,'FALLBACK_ONLY');assert.equal(dto.components[0].text,'No interpretation or next focus is shown here.');}
  const processes=await cold(s);await analytics(s.page,source);
  const warm=await coverage(s,async()=>{await normal(s.page,s);await s.page.locator('[data-nav="history"]').click();await s.page.locator('[data-nav="home"]').click();});for(const n of Object.values(warm))assert.ok(n>0);await analytics(s.page,source);await normal(s.page,s);await analytics(s.page,source);await storage(s,source);assert.deepEqual(await exportState(s),source);
  return {componentCount:count,mode:dto.mode,canonicalBodies:dto.components.map(c=>c.text),counts,warmCounts:warm,...processes,offlineColdWarm:true,businessStateExportUnchanged:true,cache:await complete(s,on)};
 }));
 await sub(t,'PP-IMPORT-01',()=>using(mf3,async s=>{
  await initial(s,on);await selected(s,on);assert.equal((await analytics(s.page,mf3)).components.length,5);const oldHost=await s.page.locator(HOST).elementHandle();assert.ok(oldHost);
  const counts=await coverage(s,()=>importState(s,mf4));for(const n of Object.values(counts))assert.ok(n>0);assert.equal(await oldHost.evaluate(h=>h.isConnected),false);assert.equal((await analytics(s.page,mf4)).components.length,9);await oldHost.dispose();await storage(s,mf4);assert.deepEqual(await exportState(s),mf4);await cold(s);await analytics(s.page,mf4);
  return {acceptedImport:true,componentsBefore:5,componentsAfter:9,oldHostDetached:true,counts,latestCommittedStateOnly:true,stateAndExportEqualImport:true};
 }));
 await sub(t,'PP-INSTALL-FAIL',()=>using(mf4,async s=>{
  await initial(s,off);await selected(s,off);const next=createStagedRelease(inputs,{generation:'offline-candidate-13',mode:'OFF'}),prior=await s.page.evaluateHandle(()=>navigator.serviceWorker.controller);publish(s,next);s.fault={url:ART,kind:'404'};
  const state=await bounded(s.page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Failed install not observed')),30000);r.addEventListener('updatefound',()=>{const w=r.installing;w.addEventListener('statechange',()=>{if(w.state==='redundant'||w.state==='installed'){clearTimeout(timer);resolve(w.state);}});},{once:true});r.update().catch(error=>{clearTimeout(timer);reject(error);});});}),31000);
  assert.equal(state,'redundant');const delivered404=s.requests.filter(x=>x.url===ART&&x.fault==='404');assert.ok(delivered404.length>0,'Injected HTTP 404 was not actually requested');assert.equal(await s.page.evaluate(h=>navigator.serviceWorker.controller===h,prior),true);await prior.dispose();assert.equal(await s.page.evaluate(name=>caches.has(name),next.cacheName),false);s.fault=null;s.offline=true;await s.context.setOffline(true);
  const counts=await coverage(s,()=>normal(s.page,s));assert.deepEqual(counts,ZERO);await noAnalytics(s);await storage(s,mf4);assert.deepEqual(await exportState(s),mf4);
  return {rejectedState:state,missingAsset:ART,deliveredHTTP404Count:delivered404.length,failedCacheRemoved:true,priorControllerPreserved:true,priorHardenedOFFUsableOffline:true,counts,priorCache:await complete(s,off)};
 }));
 await sub(t,'PP-ROLLBACK-01',()=>using(mf4,async s=>{
  await initial(s,off);await selected(s,off);await activate(s,await waiting(s,on));await analytics(s.page,mf4);const rollback=rollbackStagedRelease(off,'rollback-11');verifyStagedRelease(rollback);assert.notEqual(rollback.releaseDigest,off.releaseDigest);assert.notEqual(rollback.cacheName,on.cacheName);assert.deepEqual(rollback.bootstrap,off.bootstrap);assert.deepEqual(rollback.entry,off.entry);for(const[url,bytes]of off.assets)assert.deepEqual(rollback.assets.get(url),bytes);
  const response=await activate(s,await waiting(s,rollback));assert.deepEqual(await response.body(),off.entry);const counts=await coverage(s,()=>normal(s.page,s));assert.deepEqual(counts,ZERO);await noAnalytics(s);const processes=await cold(s);
  const warmCounts=await coverage(s,async()=>{await normal(s.page,s);await s.page.locator('[data-nav="history"]').click();await s.page.locator('[data-nav="home"]').click();});assert.deepEqual(warmCounts,ZERO);await noAnalytics(s);await storage(s,mf4);assert.deepEqual(await exportState(s),mf4);
  return {freshGeneration:rollback.inventory.generation,freshCache:rollback.cacheName,priorHardenedOFFBootstrapSha256:sha256(off.bootstrap),rollbackBootstrapSha256:sha256(rollback.bootstrap),priorOFFEntrySha256:sha256(off.entry),rollbackEntrySha256:sha256(rollback.entry),allPriorAssetsIdentical:true,previousAllowRemoved:true,counts,warmCounts,...processes,stateAndExportPreserved:true,cache:await complete(s,rollback)};
 }));
 assert.deepEqual(failures,[]);assert.equal(cases,IDS.length);assert.deepEqual([...rows.keys()].sort(),[...IDS].sort());assert.ok([...rows.values()].every(r=>r.status==='PASS'));assert.equal(git('status','--porcelain').toString(),initialGit);
 const finalInputs=readInputs(ROOT);assert.equal(finalInputs.frozenSourceTreeSha256,inputs.frozenSourceTreeSha256);assert.equal(finalInputs.sourceAppSha256,inputs.sourceAppSha256);const browserAfter=sha256(fs.readFileSync(browserPath));assert.equal(browserAfter,browserBefore);
 const report={status:'PASS',phase:'PRIVATE_HARDENED_PUBLIC_PROPOSAL',candidateCommit:git('rev-parse','HEAD').toString().trim(),integrationCommit:S3,expectedMountPath:MOUNT,publicDeploymentPerformed:false,publicActivationPerformed:false,productionChanged:false,sourceFlag:'OFF',frozenUnchanged:true,offReleaseDigest:off.releaseDigest,onReleaseDigest:on.releaseDigest,rows:IDS.map(id=>rows.get(id)),tests:cases,skipped:0,todo:0,browser:{path:browserPath,version:browserVersion,sha256Before:browserBefore,sha256After:browserAfter}};
 if(evidence)fs.writeFileSync(path.join(evidence,'public-proposal-matrix.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report,null,2));
});
